---
# Main playbook to setup complete Rancher cluster
- name: Setup Rancher Master Node
  hosts: master
  become: yes
  gather_facts: yes
  roles:
    - master
  tags:
    - master
    - rancher

- name: Create Rancher cluster and get registration command
  hosts: master
  become: yes
  gather_facts: no
  tags:
    - cluster
    - registration
  tasks:
    - name: Wait for Rancher API to be fully ready
      uri:
        url: "https://{{ ansible_host }}/v3"
        method: GET
        validate_certs: no
        status_code: 200
      register: api_check
      until: api_check.status == 200
      retries: 30
      delay: 10

    - name: Check if cluster already exists
      uri:
        url: "https://{{ ansible_host }}/v3/clusters"
        method: GET
        validate_certs: no
        status_code: 200
      register: clusters_check
      ignore_errors: true

    - name: Display manual cluster creation instructions
      debug:
        msg:
          - "==========================================="
          - "MANUAL CLUSTER SETUP REQUIRED"
          - "==========================================="
          - ""
          - "Please complete these steps:"
          - ""
          - "1. Open Rancher UI: https://{{ ansible_host }}"
          - "2. Login with the bootstrap password"
          - "3. Create a new cluster (Custom or Import existing)"
          - "4. Copy the worker registration command"
          - "5. The registration command will be automatically distributed to workers"
          - ""
          - "Alternatively, you can create a cluster via Rancher API"
          - "and store the registration command in /tmp/rancher_registration_cmd.sh"
          - ""
          - "Once ready, run the workers playbook:"
          - "  ansible-playbook -i inventory.ini site.yml --tags workers"
          - ""
          - "==========================================="

- name: Setup Rancher Worker Nodes
  hosts: workers
  become: yes
  gather_facts: yes
  roles:
    - worker
  tags:
    - workers
    - agents
