---
# Main playbook to setup complete Rancher cluster
- name: Setup Rancher Master Node
  hosts: master
  become: yes
  gather_facts: yes
  roles:
    - master
  tags:
    - master
    - rancher

- name: Setup Rancher Worker Nodes
  hosts: workers
  become: yes
  gather_facts: yes
  roles:
    - worker
  tags:
    - workers
    - agents
